lists = ["cat", "dog", "monkey"]
print(lists)
print("")
print("the length of the list: ", len(lists))
print("")
print("type of the lists ", type(lists))
print("")
print("print first item ", lists[0])
print("")
print("print second and third item ", lists[1:3])
print("")
print("print last item ", lists[-1])
print("")
print("print third last and second last item ", lists[-3:-1])
print("")